default_language_version:
  python: python3.11

repos:
  - repo: https://github.com/pycqa/flake8
    rev: 3.9.1
    hooks:
      - id: flake8
        entry: pflake8
        additional_dependencies: [pyproject-flake8]

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args: ["--py311-plus"]

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.2.0
    hooks:
      - id: mypy
        additional_dependencies:
          - pydantic
          - types-requests
          - types-python-dateutil
          - types-paramiko
        args: [ "--ignore-missing-imports", "--no-strict-optional", "--explicit-package-bases", "--namespace-packages"]
        exclude: integrations/opus/

  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.9.0
    hooks:
      - id: reorder-python-imports

  - repo: https://github.com/magenta-aps/pre-commit-hooks
    rev: 477acf0d
    hooks:
      - id: auto-ticket-prepare-commit
      - id: auto-ticket-commit
