repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.0
    hooks:
      - id: ruff
        args: [--fix]
        language: system
      - id: ruff-format
        language: system

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.14.1
    hooks:
      - id: mypy
        language: system
        args:
          [
            "--ignore-missing-imports",
            "--strict-optional",
            "--explicit-package-bases",
            "--namespace-packages",
          ]
        exclude: integrations/opus/
