# SPDX-FileCopyrightText: 2019-2020 Magenta ApS
# SPDX-License-Identifier: MPL-2.0

version: '3.7'

services:

  import_gir:
    build:
      context: ../..
      dockerfile: integrations/gir/docker/Dockerfile
