import pytest
from fastramqpi.depends import LegacyGraphQLSession

from ...autogenerated_graphql_client import GraphQLClient
from ...gql_lora_cache_async import GQLLoraCache


@pytest.mark.integration_test
async def test_read_engagements(
    legacy_graphql_session: LegacyGraphQLSession,
    graphql_client: GraphQLClient,
) -> None:
    gql_cache = GQLLoraCache(
        graphql_session=legacy_graphql_session, codegen_client=graphql_client
    )
    engagements_old = await gql_cache._fetch_engagements()
    engagements_new = await gql_cache._fetch_engagements_codegen()

    assert engagements_old == engagements_new
