"""create tables

Revision ID: 5dd1b1f38a0b
Revises:
Create Date: 2023-10-25 07:54:55.623450

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5dd1b1f38a0b"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "adresser",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("bruger_uuid", sa.String(length=36), nullable=True),
        sa.Column("enhed_uuid", sa.String(length=36), nullable=True),
        sa.Column("værdi", sa.String(length=250), nullable=True),
        sa.Column("dar_uuid", sa.String(length=36), nullable=True),
        sa.Column("adressetype_uuid", sa.String(length=36), nullable=True),
        sa.Column("adressetype_bvn", sa.String(length=250), nullable=False),
        sa.Column("adressetype_scope", sa.String(length=250), nullable=False),
        sa.Column("adressetype_titel", sa.String(length=250), nullable=False),
        sa.Column("synlighed_uuid", sa.String(length=36), nullable=True),
        sa.Column("synlighed_scope", sa.String(length=250), nullable=True),
        sa.Column("synlighed_titel", sa.String(length=250), nullable=True),
        sa.Column("startdato", sa.String(length=10), nullable=True),
        sa.Column("slutdato", sa.String(length=10), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "brugere",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("bvn", sa.String(length=250), nullable=False),
        sa.Column("fornavn", sa.String(length=250), nullable=True),
        sa.Column("efternavn", sa.String(length=250), nullable=True),
        sa.Column("kaldenavn_fornavn", sa.String(length=250), nullable=True),
        sa.Column("kaldenavn_efternavn", sa.String(length=250), nullable=True),
        sa.Column("cpr", sa.String(length=250), nullable=True),
        sa.Column("startdato", sa.String(length=10), nullable=True),
        sa.Column("slutdato", sa.String(length=10), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "dar_adresser",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("vejkode", sa.String(length=8), nullable=True),
        sa.Column("vejnavn", sa.String(length=250), nullable=True),
        sa.Column("husnr", sa.String(length=8), nullable=True),
        sa.Column("etage", sa.String(length=16), nullable=True),
        sa.Column("dør", sa.String(length=8), nullable=True),
        sa.Column("postnr", sa.String(length=8), nullable=True),
        sa.Column("postnrnavn", sa.String(length=250), nullable=True),
        sa.Column("kommunekode", sa.String(length=8), nullable=True),
        sa.Column("adgangsadresseid", sa.String(length=36), nullable=True),
        sa.Column("betegnelse", sa.String(length=250), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "engagementer",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("bruger_uuid", sa.String(length=36), nullable=True),
        sa.Column("enhed_uuid", sa.String(length=36), nullable=True),
        sa.Column("bvn", sa.String(length=250), nullable=False),
        sa.Column("arbejdstidsfraktion", sa.Integer(), nullable=True),
        sa.Column("engagementstype_uuid", sa.String(length=36), nullable=True),
        sa.Column("engagementstype_titel", sa.String(length=250), nullable=False),
        sa.Column("primærtype_uuid", sa.String(length=36), nullable=True),
        sa.Column("primærtype_titel", sa.String(length=250), nullable=True),
        sa.Column("stillingsbetegnelse_uuid", sa.String(length=36), nullable=True),
        sa.Column("stillingsbetegnelse_titel", sa.String(length=250), nullable=False),
        sa.Column("primær_boolean", sa.Boolean(), nullable=True),
        sa.Column("udvidelse_1", sa.String(length=250), nullable=True),
        sa.Column("udvidelse_2", sa.String(length=250), nullable=True),
        sa.Column("udvidelse_3", sa.String(length=250), nullable=True),
        sa.Column("udvidelse_4", sa.String(length=250), nullable=True),
        sa.Column("udvidelse_5", sa.String(length=250), nullable=True),
        sa.Column("udvidelse_6", sa.String(length=250), nullable=True),
        sa.Column("udvidelse_7", sa.String(length=250), nullable=True),
        sa.Column("udvidelse_8", sa.String(length=250), nullable=True),
        sa.Column("udvidelse_9", sa.String(length=250), nullable=True),
        sa.Column("udvidelse_10", sa.String(length=250), nullable=True),
        sa.Column("startdato", sa.String(length=10), nullable=True),
        sa.Column("slutdato", sa.String(length=10), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "enheder",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("navn", sa.String(length=250), nullable=False),
        sa.Column("bvn", sa.String(length=250), nullable=False),
        sa.Column("forældreenhed_uuid", sa.String(length=36), nullable=True),
        sa.Column("enhedstype_uuid", sa.String(length=36), nullable=True),
        sa.Column("enhedstype_titel", sa.String(length=250), nullable=False),
        sa.Column("enhedsniveau_uuid", sa.String(length=36), nullable=True),
        sa.Column("enhedsniveau_titel", sa.String(length=250), nullable=True),
        sa.Column("organisatorisk_sti", sa.String(length=1000), nullable=True),
        sa.Column("leder_uuid", sa.String(length=36), nullable=True),
        sa.Column("fungerende_leder_uuid", sa.String(length=36), nullable=True),
        sa.Column("opmærkning_uuid", sa.String(length=36), nullable=True),
        sa.Column("opmærkning_titel", sa.String(length=250), nullable=True),
        sa.Column("startdato", sa.String(length=10), nullable=True),
        sa.Column("slutdato", sa.String(length=10), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "enhedssammenkobling",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("enhed1_uuid", sa.String(length=36), nullable=True),
        sa.Column("enhed2_uuid", sa.String(length=36), nullable=True),
        sa.Column("startdato", sa.String(length=10), nullable=True),
        sa.Column("slutdato", sa.String(length=10), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "facetter",
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("bvn", sa.String(length=250), nullable=False),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_table(
        "it_forbindelser",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("it_system_uuid", sa.String(length=36), nullable=True),
        sa.Column("bruger_uuid", sa.String(length=36), nullable=True),
        sa.Column("enhed_uuid", sa.String(length=36), nullable=True),
        sa.Column("brugernavn", sa.String(length=250), nullable=True),
        sa.Column("primær_boolean", sa.Boolean(), nullable=True),
        sa.Column("startdato", sa.String(length=10), nullable=True),
        sa.Column("slutdato", sa.String(length=10), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "it_systemer",
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("navn", sa.String(length=250), nullable=False),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_table(
        "klasser",
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("bvn", sa.String(length=250), nullable=False),
        sa.Column("titel", sa.String(length=250), nullable=False),
        sa.Column("facet_uuid", sa.String(length=36), nullable=True),
        sa.Column("facet_bvn", sa.String(length=250), nullable=False),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_table(
        "kle",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("enhed_uuid", sa.String(length=36), nullable=True),
        sa.Column("kle_aspekt_uuid", sa.String(length=36), nullable=True),
        sa.Column("kle_aspekt_titel", sa.String(length=250), nullable=False),
        sa.Column("kle_nummer_uuid", sa.String(length=36), nullable=True),
        sa.Column("kle_nummer_titel", sa.String(length=250), nullable=False),
        sa.Column("startdato", sa.String(length=10), nullable=True),
        sa.Column("slutdato", sa.String(length=10), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "leder_ansvar",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("leder_uuid", sa.String(length=36), nullable=True),
        sa.Column("lederansvar_uuid", sa.String(length=36), nullable=True),
        sa.Column("lederansvar_titel", sa.String(length=250), nullable=False),
        sa.Column("startdato", sa.String(length=10), nullable=True),
        sa.Column("slutdato", sa.String(length=10), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ledere",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("bruger_uuid", sa.String(length=36), nullable=True),
        sa.Column("enhed_uuid", sa.String(length=36), nullable=True),
        sa.Column("ledertype_uuid", sa.String(length=36), nullable=True),
        sa.Column("ledertype_titel", sa.String(length=250), nullable=False),
        sa.Column("niveautype_uuid", sa.String(length=36), nullable=True),
        sa.Column("niveautype_titel", sa.String(length=250), nullable=False),
        sa.Column("startdato", sa.String(length=10), nullable=True),
        sa.Column("slutdato", sa.String(length=10), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "orlover",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("bvn", sa.String(length=250), nullable=False),
        sa.Column("bruger_uuid", sa.String(length=36), nullable=True),
        sa.Column("orlovstype_uuid", sa.String(length=36), nullable=True),
        sa.Column("orlovstype_titel", sa.String(length=250), nullable=False),
        sa.Column("engagement_uuid", sa.String(length=36), nullable=True),
        sa.Column("startdato", sa.String(length=10), nullable=True),
        sa.Column("slutdato", sa.String(length=10), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "roller",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("bruger_uuid", sa.String(length=36), nullable=True),
        sa.Column("enhed_uuid", sa.String(length=36), nullable=True),
        sa.Column("rolletype_uuid", sa.String(length=36), nullable=True),
        sa.Column("rolletype_titel", sa.String(length=250), nullable=False),
        sa.Column("startdato", sa.String(length=10), nullable=True),
        sa.Column("slutdato", sa.String(length=10), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tilknytninger",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("bvn", sa.String(length=250), nullable=False),
        sa.Column("bruger_uuid", sa.String(length=36), nullable=True),
        sa.Column("enhed_uuid", sa.String(length=36), nullable=True),
        sa.Column("tilknytningstype_uuid", sa.String(length=36), nullable=True),
        sa.Column("tilknytningstype_titel", sa.String(length=250), nullable=True),
        sa.Column("stillingsbetegnelse_uuid", sa.String(length=36), nullable=True),
        sa.Column("stillingsbetegnelse_titel", sa.String(length=250), nullable=True),
        sa.Column("it_forbindelse_uuid", sa.String(length=36), nullable=True),
        sa.Column("startdato", sa.String(length=10), nullable=True),
        sa.Column("slutdato", sa.String(length=10), nullable=True),
        sa.Column("primær_boolean", sa.Boolean(), nullable=True),
        sa.Column("faglig_organisation", sa.String(length=250), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tilknytninger")
    op.drop_table("roller")
    op.drop_table("orlover")
    op.drop_table("ledere")
    op.drop_table("leder_ansvar")
    op.drop_table("kle")
    op.drop_table("klasser")
    op.drop_table("it_systemer")
    op.drop_table("it_forbindelser")
    op.drop_table("facetter")
    op.drop_table("enhedssammenkobling")
    op.drop_table("enheder")
    op.drop_table("engagementer")
    op.drop_table("dar_adresser")
    op.drop_table("brugere")
    op.drop_table("adresser")
    # ### end Alembic commands ###
