[tool.poetry]
name = "SDLon"
version = "0.1.0"
description = "OS2mo SDLoen integration"
authors = ["Magenta <info@magenta.dk>"]
license = "MPL-2.0"
readme = "README.rst"
homepage = "https://magenta.dk/"
repository = "https://git.magenta.dk/rammearkitektur/os2mo-data-import-and-export"
keywords = ["os2mo", "dipex", "sdloen"]

[tool.poetry.dependencies]
python = "^3.9"
more-itertools = "^8.12.0"
requests = "^2.27.1"
xmltodict = "^0.12.0"
ra-utils = "0.4.0"
pydantic = "^1.9.0"
anytree = "^2.8.0"
fastapi = "^0.75.0"
lxml = "^4.8.0"
os2mo-data-import = "^0.0.2"
ramodels = "^5.4.0"
os2mo-dar-client = "^0.2.3"
tqdm = "^4.63.0"
uvicorn = "^0.17.6"

[tool.poetry.dev-dependencies]
pytest = "^7.0.1"
hypothesis = "^6.39.3"
black = "^22.1.0"
reorder-python-imports = "^3.0.1"
parameterized = "^0.8.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
