# SPDX-FileCopyrightText: 2019-2020 Magenta ApS
# SPDX-License-Identifier: MPL-2.0
services:
  os2sync_export:
    build:
      context: .
    environment:
      
      AUTH_SERVER: "http://keycloak:8080/auth"
      CLIENT_ID: "dipex"
      CLIENT_SECRET: "603f1c82-d012-4d04-9382-dbe659c533fb"
      MORA_BASE: http://mo:80
      MUNICIPALITY: 1234
      OS2SYNC_API_URL: "stub"
      OS2SYNC_HASH_CACHE: /tmp/hash_cache
      OS2SYNC_TOP_UNIT_UUID: "f06ee470-9f17-566f-acbe-e938112d46d9"
      LOG_LEVEL: INFO

    command: "uvicorn os2sync_export.main:app --host 0.0.0.0 --reload"
    ports:
      - 127.0.0.1:8000:8000/tcp
    volumes:
      - ./:/app/
    networks:
      - os2mo_default

networks:
  os2mo_default:
    external: true