[tool.poetry]
name = "os2sync_export"
version = "0.1.0"
description = ""
authors = ["Benjamin Lyng Jørgensen <blj@magenta-aps.dk>"]

[tool.poetry.dependencies]
python = "^3.9"
dipex = "^2.33.3"

[tool.poetry.dev-dependencies]
pytest = "^6.2"
pre-commit = "^2.18.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
