[tool.poetry]
name = "os2sync_export"
version = "0.1.0"
description = "Integration from OS2mo to OS2Sync"
authors = ["Magenta ApS <info@magenta.dk>"]
license = "MPL-2.0"
readme = "readme.rst"
homepage = "https://magenta.dk/"
repository = "https://git.magenta.dk/rammearkitektur/os2mo-data-import-and-export"
keywords = ["os2mo", "dipex", "os2sync"]

[tool.poetry.dependencies]
python = "^3.10"
tqdm = "^4.64.1"
more-itertools = "^9.0.0"
pytest = "^6.2.5"
click = "^8.1.3"
Jinja2 = "^3.1.2"
ra-utils = "^1.7.1"
requests = "^2.28.2"
SQLAlchemy = "^1.4.46"
pydantic = "^1.10.4"
fastapi = "^0.88.0"
uvicorn = "^0.20.0"
sentry-sdk = "^1.13.0"
setuptools = "^66.0.0"
raclients = "^3.0.3"

[tool.poetry.dev-dependencies]
pytest = "^6.2"
pre-commit = "^2.18.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
