# SPDX-FileCopyrightText: 2019-2020 Magenta ApS
# SPDX-License-Identifier: MPL-2.0
services:
  sql_export:
    build: .
    command: ["uvicorn", "sql_export.main:app", "--host", "0.0.0.0", "--reload"]
    environment:
      AUTH_SERVER: "http://keycloak:8080/auth"

      MORA_BASE: "http://mo"
      CLIENT_ID: "dipex"
      CLIENT_SECRET: "603f1c82-d012-4d04-9382-dbe659c533fb"

      MOX_BASE: "http://mox"
      LORA_CLIENT_SECRET: "a091ed82-6e82-4efc-a8f0-001e2b127853"

      SQL_EXPORT_HOST: export-db
      SQL_EXPORT_PASSWORD: mysecretpassword
    ports:
      - 7000:8000/tcp
    volumes:
      - ./:/app/sql_export/
    networks:
      - os2mo_default
      - sql_export

  export-db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: actualstate
    tmpfs:
      - /var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - sql_export

networks:
  os2mo_default:
    external: true
  sql_export:
