# SPDX-FileCopyrightText: 2019-2020 Magenta ApS
# SPDX-License-Identifier: MPL-2.0
services:
  sql_export:
    tty: true
    stdin_open: true
    build: .
    command: ["uvicorn", "--factory", "sql_export.main:create_app", "--host", "0.0.0.0", "--reload"]
    environment:
      AUTH_SERVER: "http://keycloak:8080/auth"
      CLIENT_ID: "dipex"
      CLIENT_SECRET: "603f1c82-d012-4d04-9382-dbe659c533fb"

      MO_URL: "http://mo:5000"
      MORA_BASE: "http://mo:5000"
      MOX_BASE: "http://mo:5000/lora"

      LOG_LEVEL: INFO

      ACTUAL_STATE__TYPE: Postgres
      ACTUAL_STATE__HOST: export-db
      ACTUAL_STATE__DB_NAME: actualstate
      ACTUAL_STATE__USER: postgres
      ACTUAL_STATE__PASSWORD: mysecretpassword
      FASTRAMQPI__AMQP__URL: "amqp://guest:guest@msg-broker:5672/"
      EVENTDRIVEN: "true"
      USE_NEW_CACHE: "true"
      FULL_HISTORY: "true"
    ports:
      - 8789:8000/tcp
    volumes:
      - ./:/opt/sql_export/
    networks:
      - os2mo_default
      - sql_export

  export-db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: actualstate
    tmpfs:
      - /var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - sql_export

networks:
  os2mo_default:
    external: true
  sql_export:
