[tool.poetry]
name = "SQLExport"
version = "0.1.0"
description = "Actual State SQL export"
authors = ["Magenta <info@magenta.dk>"]
license = "MPL-2.0"
readme = "README.rst"
homepage = "https://magenta.dk/"
repository = "https://git.magenta.dk/rammearkitektur/os2mo-data-import-and-export"
keywords = ["os2mo", "dipex", "sql_export"]

[tool.poetry.dependencies]
python = "^3.8"
pymssql = "^2.2.5"
SQLAlchemy = "^1.4.39"
alembic = "^1.8.1"
mysqlclient = "^2.1.1"
pyodbc = "^4.0.34"
lora-utils = {git = "https://github.com/magenta-aps/lora-utils.git", rev = "master"}
uvicorn = "^0.18.2"
ra-utils = "^1.2.0"
tqdm = "^4.64.0"
fastapi = "^0.79.0"
prometheus-fastapi-instrumentator = "^5.8.2"
requests = "^2.28.1"
os2mo-dar-client = "^1.0.1"
os2mo-data-import = "^2.41.1"
retrying = "^1.3.3"
psycopg2-binary = "^2.9.3"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
hypothesis = "^6.39.3"
black = "^22.1.0"
reorder-python-imports = "^3.0.1"
parameterized = "^0.7.4"
pre-commit = "^2.17.0"
mypy = "^0.971"
alchemy-mock = "^0.4.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
asyncio_mode = "strict"

[tool.mypy]
python_version = "3.10"
warn_return_any = "True"
warn_unused_configs = "True"
check_untyped_defs = "True"
disallow_untyped_defs = "True"
plugins = "pydantic.mypy"

[tool.flake8]
max-line-length = 88
exclude = [
"__pycache__", ".mypy_cache", ".pytest_cache"
]
